name: artifact-unit-tests
on:
  workflow_dispatch:

jobs:
  build:
    name: Build    
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: node -v

    - name: Set env variables
      uses: ./packages/artifact/__tests__/ci-test-action/

    - name: Install root npm packages
      run: npm ci

    - name: Compile artifact package
      run: |
        npm ci
        npm run tsc
      working-directory: packages/artifact

    - name: Set artifact file contents
      run: |
        echo "gzip-artifact-content=Some large amount of text that has a compression ratio that is greater than 100%. If greater than 100%, gzip is used to upload the file" >> "$Env:GITHUB_ENV"

    - name: Create files that will be uploaded
      run: |
        mkdir artifact-path
        echo ${{ env.gzip-artifact-content }} > artifact-path/gzip.txt

    - name: Upload artifacts using uploadArtifact()
      run: |
        node -e "Promise.resolve(require('./packages/artifact/lib/artifact-client').create().uploadArtifact('my-artifact-2',['artifact-path/gzip.txt'], '${{ github.workspace }}'))"

    - name: Download artifacts using downloadArtifact()
      run: |
        mkdir artifact-2-directory
        node -e "Promise.resolve(require('./packages/artifact/lib/artifact-client').create().downloadArtifact('my-artifact-2','artifact-2-directory'))"

    - name: Verify downloadArtifact()
      run: |
        cat "artifact-2-directory/artifact-path/gzip.txt"

    - name: Download artifacts using downloadAllArtifacts()
      run: |
        mkdir multi-artifact-directory
        node -e "Promise.resolve(require('./packages/artifact/lib/artifact-client').create().downloadAllArtifacts('multi-artifact-directory'))"
    
    - name: Verify downloadAllArtifacts()
      run: |
        cat "multi-artifact-directory/my-artifact-2/artifact-path/gzip.txt"

